=== shopware5/shopware/engine/Shopware/Components/Plugin/schema/config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xsd:element name="config" type="config"/>

    <xsd:complexType name="config">
        <xsd:sequence>
            <xsd:element name="label" type="translatableString" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="description" type="translatableString" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="elements" type="elementsType"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="elementsType">
        <xsd:sequence>
            <xsd:element name="element" type="elementType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="elementType">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="label" type="translatableString" maxOccurs="unbounded"/>
            <xsd:element name="value" type="xsd:string" minOccurs="0"/>
            <xsd:element name="description" type="translatableString" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="store" type="store" minOccurs="0">
                <xsd:unique name="uniqueStoreOptionValue">
                    <xsd:selector xpath="option/value"/>
                    <xsd:field xpath="."/>
                </xsd:unique>
            </xsd:element>
            <xsd:element name="options" type="options" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute name="type" type="type" default="text"/>
        <xsd:attribute name="required" type="xsd:boolean" default="false"/>
        <xsd:attribute name="scope" type="scope" default="locale"/>
    </xsd:complexType>

    <xsd:complexType name="options">
        <xsd:sequence>
            <xsd:any processContents="lax" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="text"/>
            <xsd:enumeration value="password"/>
            <xsd:enumeration value="textarea"/>
            <xsd:enumeration value="boolean"/>
            <xsd:enumeration value="color"/>
            <xsd:enumeration value="date"/>
            <xsd:enumeration value="datetime"/>
            <xsd:enumeration value="time"/>
            <xsd:enumeration value="interval"/>
            <xsd:enumeration value="html"/>
            <xsd:enumeration value="mediaselection"/>
            <xsd:enumeration value="number"/>
            <xsd:enumeration value="select"/>
            <xsd:enumeration value="selecttree"/>
            <xsd:enumeration value="combo"/>
            <xsd:enumeration value="combotree"/>
            <xsd:enumeration value="button"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="store" mixed="true">
        <xsd:sequence>
            <xsd:element type="storeOption" name="option" minOccurs="0" maxOccurs="unbounded">
                <xsd:unique name="uniqueStoreOptionLabel">
                    <xsd:selector xpath="label"/>
                    <xsd:field xpath="@lang"/>
                </xsd:unique>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute type="storeType" name="type" use="optional" default="xml"/>
    </xsd:complexType>

    <xsd:simpleType name="storeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="xml"/>
            <xsd:enumeration value="extjs"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="storeOption" mixed="true">
        <xsd:sequence>
            <xsd:element name="value" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="label" type="translatableString" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="scope">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="locale"/>
            <xsd:enumeration value="shop"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="translatableString">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="lang" type="xsd:language" default="en"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

</xsd:schema>

=== shopware5/shopware/tests/Unit/Components/Plugin/XmlReader/examples/config/config.xml
<?xml version="1.0" encoding="utf-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../../../../../../engine/Shopware/Components/Plugin/schema/config.xsd">

    <label lang="en">My Form Label</label>
    <label lang="de">Mein Form</label>

    <description lang="en">My Form description</description>
    <description lang="de">Meine Form Beschreibung</description>

    <elements>
        <element scope="locale" required="true" type="text">
            <name>my-field</name>
            <label lang="de">Mein textfeld</label>
            <label lang="en">My Textfield</label>
            <value>Some default value</value>
            <description lang="de">Meine Feld Beschreibung</description>
            <description lang="en">My Field description</description>
            <options>
                <minValue>1</minValue>
                <maxValue>2</maxValue>
            </options>
        </element>
        <element scope="locale" required="true" type="text">
            <name>my-field</name>
            <label lang="de">Mein textfeld</label>
            <label lang="en">My Textfield</label>
            <value>Some default value</value>
            <description lang="de">Meine Feld Beschreibung</description>
            <description lang="en">My Field description</description>
            <store>
                <option>
                    <value>value</value>
                    <label>label</label>
                </option>
            </store>
        </element>
    </elements>
</config>
